CREATE TABLE IF NOT EXISTS dingtalk_personal_message (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    workspace_id UUID NOT NULL,
    comment_id UUID NOT NULL,
    sender_user_id UUID NOT NULL,
    sender_ding_user_id TEXT NOT NULL,
    sender_union_id TEXT,
    sender_corp_id TEXT,
    recipient_user_id UUID NOT NULL,
    recipient_ding_user_id TEXT NOT NULL,
    markdown TEXT NOT NULL,
    idempotency_key TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN (
        'pending',
        'leased',
        'waiting_for_dws_login',
        'waiting_for_identity',
        'delivered',
        'failed',
        'expired',
        'cancelled'
    )),
    attempts INTEGER NOT NULL DEFAULT 0 CHECK (attempts >= 0),
    available_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at TIMESTAMPTZ NOT NULL DEFAULT (now() + interval '24 hours'),
    lease_owner TEXT,
    leased_until TIMESTAMPTZ,
    dws_open_task_id TEXT,
    dws_open_message_id TEXT,
    last_error_code TEXT,
    last_error_message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    delivered_at TIMESTAMPTZ
);
